[package]
name = "steam_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
derive-getters = "0.5.0"
reqwest = { version = "0.12.8", features = ["blocking"] }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
